name: trigger-me-not-backend

services:
  db:
    container_name: trigger-me-not-db
    image: postgres:17
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    restart:
      unless-stopped

  backend:
    container_name: trigger-me-not-api
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    networks:
      - app-network
    restart:
      unless-stopped

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
